baseurl = "http://localhost:1313/"
languageCode = "en-us"
title = "PBFAM"
theme = "hugo-creative-theme"
canonifyurls = true

[params]

    # You can use Markdown syntax for urls [text](//url.to/source) for
    # most longer texts.

    # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
    # for more icons. The icons are represented by their corresponding
    # CSS class.

    # All projects of the portfolio are defined in their own files.
    # You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
    # folder into the 'data' directory at the root of this Hugo site.
    # For more informtion take a look at the README.

    # To provide some metadata for search engines feel free to add a few
    # information about you and your website.
    name = "GE Global Research"
    description = "GE Research Center Niskayuna, NY"

    # The path must be relative to the static folder
    favicon = "favicon.png"

    # Navigation
    [params.navigation]
        brand = "PBFAM"

    [params.navigation.links]
        github    = "https://github.com/pbfam"
        docs      = "http://github.com/pbfam/docs"
        about     = "/about"

    # Hero section
    [params.hero]
        # To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
        slogan     = "PBFAM"
        subtitle   = "Open-Source Protocols for Powder Bed Fusion Additive Manufacturing"
        buttonLink = "#approach"
        buttonText = "Learn More"

    # Approach section
    [params.approach]
        headline    = "What is Predix Edge?"
        subsection1 = "Tiered Hardware/Software Alignment"
        subsection2 = "Reference Architecture"
        subsection3 = "Continuous Integration/Development"
    