baseurl = "http://localhost:1313/"
languageCode = "en-us"
title = "Predix Edge"
theme = "hugo-creative-theme"
canonifyurls = true

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more informtion take a look at the README.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "GE Global Research"
	description = "GE Research Center Niskayuna, NY"

	# The path must be relative to the static folder
	favicon = "favicon.png"

	# Navigation
	[params.navigation]
		brand = "Predix Edge Î²eta"

		[params.navigation.links]
            github    = "https://github.build.ge.com/PredixEdge"
            registry  = "https://registry.gear.ge.com"
			docs      = "http://docs.edge.research.ge.com"
            guides    = "http://guides.edge.research.ge.com"
            contact   = "#contact"

	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Predix Edge"
		subtitle   = "Container driven development & deployment solution for the [Predix](//predix.io) platform"
		buttonLink = "#approach"
        buttonText = "Learn More"

	# Approach section
	[params.approach]
		headline    = "What is Predix Edge?"
		subsection1 = "Tiered Hardware/Software Alignment"
        subsection2 = "Reference Architecture"
        subsection3 = "Continuous Integration/Development"
        
	# Features section
	[params.features]
		headline = "Beta Features"

        [[params.features.list]]
            icon = "fa-reorder"
            title = "Container Support"
            description = "Multi-architecture container runtime support and build system."

        [[params.features.list]]
			icon = "fa-th-large"
			title = "Multi-container Applications"
			description = "Define and launch apps comprising several containers."

		[[params.features.list]]
            icon = "fa-cloud"
            title = "Trusted Registry"
            description = "GE managed image tree in hosted registry."

        [[params.features.list]]
            icon = "fa-comments"
            title = "Community Model"
            description = "GE shared source for cross-business development."

    # Aside section
	[params.aside]
		headline = "Get the latest Predix Edge software"
        community = "Join the Community"
    [params.aside.button]
			text = "Visit Our Github"
			link = "https://github.build.ge.com/PredixEdge"
    [params.aside.signup]
			text = "Sign Up"
			link = "https://oneidm.ge.com/faces/modules/my_groups/distribution_lists_join.xhtml"
            

	# Contact section
	[params.contact]
		headline = "Contact Us!"
		description = "Please reach out for more information about our Predix Edge. For technical requests please create issues in our github site."

		email = "edge@ge.com"
